# Generated by Django 2.1.2 on 2020-07-23 06:29

from django.db import migrations, models
import django.db.models.deletion
import win32timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CoursePart', '0001_initial'),
        ('MySite', '0006_confirmstring'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Create_Date', models.DateTimeField(default=win32timezone.now)),
                ('Course_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoursePart.Course')),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MySite.User')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'ordering': ['ID', 'Create_Date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='favorites',
            unique_together={('Course_ID', 'User_ID')},
        ),
    ]
