# Generated by Django 3.0.8 on 2020-07-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.CharField(max_length=128, unique=True)),
                ('UserName', models.CharField(max_length=128)),
                ('Password', models.CharField(max_length=256)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('JoinDate', models.EmailField(max_length=256)),
            ],
            options={
                'ordering': ['-JoinDate'],
            },
        ),
    ]
