# Generated by Django 3.0.8 on 2020-07-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-JoinDate'], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterField(
            model_name='user',
            name='JoinDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
