# Generated by Django 3.0.3 on 2020-07-12 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0003_auto_20200711_2023'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfirmString',
        ),
    ]
