# Generated by Django 3.0.3 on 2020-07-11 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('ID', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('publicBasicCompulsory', '公共基础必修'), ('publicBasicElective', '公共基础选修'), ('generalEducationCompulsory', '通识教育必修'), ('generalEducationElective', '通识教育选修'), ('professionalEducationCompulsory', '专业教育必修'), ('professionalEducationElective', '专业教育选修'), ('publicCompulsory', '公共必修'), ('publicElective', '公共选修'), ('professionalCompulsory', '专业必修'), ('professionalElective', '专业选修')], max_length=128)),
                ('teacherName', models.CharField(max_length=128)),
                ('college', models.CharField(max_length=128)),
                ('credit', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('time', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'ordering': ['ID'],
            },
        ),
    ]
