# Generated by Django 2.1.2 on 2020-07-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('社会科学与现代社会', '社会科学与现代社会'), ('科学精神与生命关怀', '科学精神与生命关怀'), ('艺术体验与审美鉴赏', '艺术体验与审美鉴赏'), ('中华文化与世界文明', '中华文化与世界文明')], max_length=128)),
                ('teacherName', models.CharField(max_length=128)),
                ('college', models.CharField(max_length=128)),
                ('credit', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'ordering': ['ID'],
            },
        ),
    ]
