# Generated by Django 3.0.3 on 2020-07-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoursePart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='time',
        ),
        migrations.AlterField(
            model_name='course',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('社会科学与现代社会', '社会科学与现代社会'), ('科学精神与生命关怀', '科学精神与生命关怀'), ('艺术体验与审美鉴赏', '艺术体验与审美鉴赏'), ('中华文化与世界文明', '中华文化与世界文明')], max_length=128),
        ),
    ]
