# Generated by Django 2.1.2 on 2020-07-24 22:22

from django.db import migrations, models
import django.db.models.deletion
import win32timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MySite', '0001_initial'),
        ('CoursePart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowseRecords',
            fields=[
                ('RecordID', models.AutoField(primary_key=True, serialize=False)),
                ('Time', models.DateTimeField(default=win32timezone.now)),
                ('Course_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoursePart.Course')),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MySite.User')),
            ],
            options={
                'verbose_name': '浏览记录',
                'verbose_name_plural': '浏览记录',
                'ordering': ['RecordID'],
            },
        ),
    ]
