# Generated by Django 3.0.3 on 2020-07-17 15:54

from django.db import migrations, models
import django.db.models.deletion
import win32timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CoursePart', '0001_initial'),
        ('MySite', '0005_evaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('Comment_ID', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('Comment_text', models.CharField(max_length=256)),
                ('Time', models.DateTimeField(default=win32timezone.now)),
                ('Comment_User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='MySite.User')),
                ('Course_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='CoursePart.Course')),
                ('To_User_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='MySite.User')),
            ],
            options={
                'verbose_name': '用户评价',
                'verbose_name_plural': '用户评价',
                'ordering': ['Comment_User_ID', 'Time'],
            },
        ),
    ]
