# Generated by Django 2.1.2 on 2020-07-25 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CourseComment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='To_Comment_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_comment', to='CourseComment.Comment'),
        ),
    ]
