# Generated by Django 2.1.2 on 2020-07-25 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CourseComment', '0002_auto_20200725_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Comment_User_ID',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='Course_ID',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='To_Comment_ID',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
