# Generated by Django 3.0.3 on 2020-07-21 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CourseComment', '0002_auto_20200718_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='To_User_ID',
        ),
        migrations.AddField(
            model_name='comment',
            name='To_Comment_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_comment', to='CourseComment.Comment'),
        ),
    ]
