# Generated by Django 2.1.2 on 2020-07-23 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CourseComment', '0005_browserecords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='browserecords',
            name='Course_ID',
        ),
        migrations.RemoveField(
            model_name='browserecords',
            name='User_ID',
        ),
        migrations.DeleteModel(
            name='BrowseRecords',
        ),
    ]
